import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { createAppleHealthSleepOrchestrator, createAppleHealthWebhookSecretLookup } from "@/lib/server/integrations";
import { hasAppleHealthServerEnv } from "@/lib/server/env";
import { verifyAppleHealthRequest } from "../verify-request";

/**
 * Apple Health sleep webhook.
 *
 * Auth (either one — see verify-request.ts): both are checked against a
 * token scoped to the specific `X-User-Id` on the request (generated by
 * that user from the Integrations page), not a shared app-wide secret.
 *   Authorization: Bearer <per-user webhook token>  + X-User-Id
 *   X-User-Id + X-Timestamp + X-Signature (HMAC, stricter, for scripted clients)
 *
 * Body: a single JSON object or array of objects matching the sleep payload
 * schema. All `*_minutes` fields are MINUTES — values >1440 are rejected.
 */

const minutesField = z.number().min(0).max(1440);

const appleHealthSleepPayloadSchema = z.object({
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  time_in_bed_minutes: minutesField.optional(),
  sleep_duration_minutes: minutesField.optional(),
  deep_sleep_minutes: minutesField.optional(),
  rem_sleep_minutes: minutesField.optional(),
  core_sleep_minutes: minutesField.optional(),
  awake_minutes: minutesField.optional(),
  sleep_efficiency_pct: z.number().min(0).max(100).optional(),
  resting_heart_rate: z.number().optional(),
  hrv: z.number().optional(),
  sleep_hrv_avg: z.number().optional(),
  sleep_avg_heart_rate: z.number().optional(),
  sleep_respiratory_rate: z.number().optional(),
  sleep_spo2_avg_pct: z.number().min(0).max(100).optional(),
});

const appleHealthSleepBodySchema = z.union([
  z.array(appleHealthSleepPayloadSchema),
  appleHealthSleepPayloadSchema.transform((item) => [item]),
]);

export async function POST(request: NextRequest) {
  if (!hasAppleHealthServerEnv()) {
    return NextResponse.json(
      { ok: false, error: "Apple Health webhook is not configured." },
      { status: 503 },
    );
  }

  const rawBody = await request.text();

  const lookupSecret = createAppleHealthWebhookSecretLookup();
  const auth = await verifyAppleHealthRequest(request, rawBody, lookupSecret);
  if (!auth.ok) {
    return NextResponse.json({ ok: false, error: auth.error }, { status: auth.status });
  }
  const userId = auth.userId;

  let body: unknown;
  try {
    body = JSON.parse(rawBody);
  } catch {
    return NextResponse.json({ ok: false, error: "Invalid JSON body." }, { status: 400 });
  }

  const parsed = appleHealthSleepBodySchema.safeParse(body);

  if (!parsed.success) {
    // Don't leak Zod internals to clients; log server-side.
    // eslint-disable-next-line no-console
    console.warn("[apple-health/sleep] invalid payload", parsed.error.flatten());
    return NextResponse.json({ ok: false, error: "invalid_payload" }, { status: 400 });
  }

  try {
    const orchestrator = createAppleHealthSleepOrchestrator();

    const result = await orchestrator.syncSleep({
      userId,
      triggerType: "webhook",
      items: parsed.data,
    });

    return NextResponse.json({
      ok: true,
      processed: result.processedItemCount,
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Sync failed.";

    return NextResponse.json({ ok: false, error: message }, { status: 500 });
  }
}
