import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import {
  createAppleHealthWebhookSecretLookup,
  createAppleHealthWorkoutOrchestrator,
} from "@/lib/server/integrations";
import { hasAppleHealthServerEnv } from "@/lib/server/env";
import { verifyAppleHealthRequest } from "../verify-request";

/**
 * Apple Health workout webhook. Carries individual completed workout
 * sessions (e.g. a Peloton ride written to Apple Health via HealthKit) —
 * logically separate from the sleep and daily-metrics webhooks, which are
 * date-keyed daily aggregates rather than discrete sessions. Maps to
 * `cardio_sessions`, deduped by `(sourceProvider, sourceExternalId)` via
 * `CardioSessionService.upsertImported()` (the same target-table dedup the
 * Strava/Peloton cardio sync orchestrators use), keyed on `workout_id` — the
 * bridge app's export template should supply HealthKit's stable per-workout
 * identifier there so re-sending the same workout is a no-op update rather
 * than a duplicate session.
 *
 * Auth (either one — see verify-request.ts): both are checked against a
 * token scoped to the specific `X-User-Id` on the request (generated by
 * that user from the Integrations page), not a shared app-wide secret.
 *   Authorization: Bearer <per-user webhook token>  + X-User-Id
 *   X-User-Id + X-Timestamp + X-Signature (HMAC, stricter, for scripted clients)
 *
 * Body: a single JSON object or array of objects matching the workout
 * payload schema.
 */

const appleHealthWorkoutPayloadSchema = z.object({
  workout_id: z.string().trim().min(1),
  workout_type: z.string().trim().min(1),
  session_kind: z.enum(["zone2", "vo2", "recovery", "other"]).optional(),
  start: z.string().datetime({ offset: true }).or(z.string().datetime()),
  end: z
    .string()
    .datetime({ offset: true })
    .or(z.string().datetime())
    .optional(),
  duration_minutes: z.number().min(0).max(1440).optional(),
  avg_heart_rate: z.number().positive().optional(),
  max_heart_rate: z.number().positive().optional(),
  distance_meters: z.number().nonnegative().optional(),
  source_name: z.string().trim().min(1).max(100).optional(),
});

const appleHealthWorkoutBodySchema = z.union([
  z.array(appleHealthWorkoutPayloadSchema),
  appleHealthWorkoutPayloadSchema.transform((item) => [item]),
]);

export async function POST(request: NextRequest) {
  if (!hasAppleHealthServerEnv()) {
    return NextResponse.json(
      { ok: false, error: "Apple Health webhook is not configured." },
      { status: 503 },
    );
  }

  const rawBody = await request.text();

  const lookupSecret = createAppleHealthWebhookSecretLookup();
  const auth = await verifyAppleHealthRequest(request, rawBody, lookupSecret);
  if (!auth.ok) {
    return NextResponse.json(
      { ok: false, error: auth.error },
      { status: auth.status },
    );
  }
  const userId = auth.userId;

  let body: unknown;
  try {
    body = JSON.parse(rawBody);
  } catch {
    return NextResponse.json(
      { ok: false, error: "Invalid JSON body." },
      { status: 400 },
    );
  }

  const parsed = appleHealthWorkoutBodySchema.safeParse(body);

  if (!parsed.success) {
    // Don't leak Zod internals to clients; log server-side.
    // eslint-disable-next-line no-console
    console.warn(
      "[apple-health/workouts] invalid payload",
      parsed.error.flatten(),
    );
    return NextResponse.json(
      { ok: false, error: "invalid_payload" },
      { status: 400 },
    );
  }

  try {
    const orchestrator = createAppleHealthWorkoutOrchestrator();

    const result = await orchestrator.syncWorkouts({
      userId,
      triggerType: "webhook",
      items: parsed.data,
    });

    return NextResponse.json({
      ok: true,
      processed: result.processedItemCount,
    });
  } catch (error) {
    console.error("[apple-health/workouts] Sync failed:", error);
    return NextResponse.json(
      { ok: false, error: "sync_failed" },
      { status: 500 },
    );
  }
}
