import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { createAppleHealthDailyMetricsOrchestrator, createAppleHealthWebhookSecretLookup } from "@/lib/server/integrations";
import { hasAppleHealthServerEnv } from "@/lib/server/env";
import { verifyAppleHealthRequest } from "../verify-request";

/**
 * Apple Health daily activity metrics webhook.
 *
 * Carries whole-body daytime activity data (steps, VO2 max, non-sleep
 * resting heart rate, exercise minutes, active energy burn) — logically
 * separate from the sleep webhook (`../sleep/route.ts`), which is scoped to
 * overnight sleep-stage and in-sleep vitals data and typically sent once per
 * morning. This endpoint is expected to be sent more frequently (e.g. every
 * few hours or once nightly) since daytime activity accrues throughout the
 * day. Same auth scheme, headers, and orchestration shape as the sleep
 * webhook — see verify-request.ts for the full security rationale.
 *
 * Auth (either one — see verify-request.ts): both are checked against a
 * token scoped to the specific `X-User-Id` on the request (generated by
 * that user from the Integrations page), not a shared app-wide secret.
 *   Authorization: Bearer <per-user webhook token>  + X-User-Id
 *   X-User-Id + X-Timestamp + X-Signature (HMAC, stricter, for scripted clients)
 *
 * Body: a single JSON object or array of objects matching the daily metrics
 * payload schema. `exercise_minutes` is MINUTES — values >1440 are rejected.
 */

const appleHealthDailyMetricsPayloadSchema = z.object({
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  steps: z.number().int().min(0).optional(),
  vo2_max: z.number().positive().optional(),
  resting_heart_rate: z.number().positive().optional(),
  exercise_minutes: z.number().min(0).max(1440).optional(),
  active_energy_kcal: z.number().min(0).optional(),
});

const appleHealthDailyMetricsBodySchema = z.union([
  z.array(appleHealthDailyMetricsPayloadSchema),
  appleHealthDailyMetricsPayloadSchema.transform((item) => [item]),
]);

export async function POST(request: NextRequest) {
  if (!hasAppleHealthServerEnv()) {
    return NextResponse.json(
      { ok: false, error: "Apple Health webhook is not configured." },
      { status: 503 },
    );
  }

  const rawBody = await request.text();

  const lookupSecret = createAppleHealthWebhookSecretLookup();
  const auth = await verifyAppleHealthRequest(request, rawBody, lookupSecret);
  if (!auth.ok) {
    return NextResponse.json({ ok: false, error: auth.error }, { status: auth.status });
  }
  const userId = auth.userId;

  let body: unknown;
  try {
    body = JSON.parse(rawBody);
  } catch {
    return NextResponse.json({ ok: false, error: "Invalid JSON body." }, { status: 400 });
  }

  const parsed = appleHealthDailyMetricsBodySchema.safeParse(body);

  if (!parsed.success) {
    // Don't leak Zod internals to clients; log server-side.
    // eslint-disable-next-line no-console
    console.warn("[apple-health/daily-metrics] invalid payload", parsed.error.flatten());
    return NextResponse.json({ ok: false, error: "invalid_payload" }, { status: 400 });
  }

  try {
    const orchestrator = createAppleHealthDailyMetricsOrchestrator();

    const result = await orchestrator.syncDailyMetrics({
      userId,
      triggerType: "webhook",
      items: parsed.data,
    });

    return NextResponse.json({
      ok: true,
      processed: result.processedItemCount,
    });
  } catch (error) {
    console.error("[apple-health/daily-metrics] Sync failed:", error);
    return NextResponse.json({ ok: false, error: "sync_failed" }, { status: 500 });
  }
}
